
# Parameters (need absolute paths)
ConfigPath = /grid_mnt/vol_home/llr/cms/cuisset/hgcal/supercls/repoForJobs/runs/superclusteringSampleDump/alessandro-v1/
Version = supercls-v13

executable = $(ConfigPath)/condor_step34.sh
transfer_input_files = $(ConfigPath)/step3_TICLv5_superclsSampleDumper.py
environment = "INDEX=$(SampleId) VERSION=$(Version) INPUT_FOLDER=$(InputFolder)"
universe = vanilla
output = logs/step34_$(SampleId).out
error = logs/step34_$(SampleId).err
log = logs/step34_$(SampleId).log
transfer_output_files = ""

request_memory = 15G
# can only be 1 or 8 on LLR T3
request_cpus = 8

T3Queue = $(T3Queue:short)
WNTag = $(WNTag:el7)
include : /opt/exp_soft/cms/t3/t3queue |
priority = -50

InputFolder = /grid_mnt/data_cms_upgrade/cuisset/supercls/alessandro_electrons/input-oppositeSign
queue SampleId from seq 351 400 |

InputFolder = /grid_mnt/data_cms_upgrade/cuisset/supercls/alessandro_electrons/input-sameSign
queue SampleId from seq 151 200 |
