
# Parameters (need absolute paths)
ConfigPath = /grid_mnt/vol_home/llr/cms/cuisset/hgcal/supercls/repoForJobs/cmssw_jobs/jobs/supercls-v16-dnn-Apr05-wahidSamples

executable = $(ConfigPath)/condor_step34.sh
transfer_input_files = $(ConfigPath)/step3_TICLv5_DNN_dumperOnly_D99.py
environment = "VERSION=$(Version) INPUT_FOLDER=$(InputFolder) INPUT_FILE=$(InputFile) MODEL_FILENAME=$(ModelFilename) DNN_WP=$(DnnWP)"
universe = vanilla
output = logs/$(Version)/step34_$(InputFile).out
error = logs/$(Version)/step34_$(InputFile).err
log = logs/$(Version)/step34_$(InputFile).log
transfer_output_files = ""

request_memory = 20G
# can only be 1 or 8 on LLR T3
request_cpus = 8

T3Queue = $(T3Queue:short)
WNTag = $(WNTag:el7)
include : /opt/exp_soft/cms/t3/t3queue |


Version = supercls-v16-dnn-Apr05_14-48
ModelFilename = supercls_v2_Apr05_14-48.onnx
DnnWP = 0.85

priority = 20
Version = supercls-v16-dnn-Apr05-wahidSamples/1p8_pt2To200
InputFolder = root://eoscms.cern.ch///eos/cms/store/group/dpg_hgcal/comm_hgcal/wredjeb/SuperClustering/CMSSW_14_X/D99/SingleElectronPU200_1p8_pt2To200/step2/
# ls -1 *.root  >/grid_mnt/vol_home/llr/cms/cuisset/hgcal/supercls/repoForJobs/cmssw_jobs/jobs/supercls-v16-dnn-Apr05-wahidSamples/files_1p8.txt
queue InputFile from [1:] files_1p8.txt

Version = supercls-v16-dnn-Apr05-wahidSamples/2p4_pt2To200
InputFolder = root://eoscms.cern.ch///eos/cms/store/group/dpg_hgcal/comm_hgcal/wredjeb/SuperClustering/CMSSW_14_X/D99/SingleElectronPU200_2p4_pt2To200/step2/
# ls -1 *.root  >/grid_mnt/vol_home/llr/cms/cuisset/hgcal/supercls/repoForJobs/cmssw_jobs/jobs/supercls-v16-dnn-Apr05-wahidSamples/files_2p4.txt
queue InputFile from files_2p4.txt




